pipeline {
    agent {
        docker {
            image 'node:10.16.3-alpine'
        }
    }

    stages {
        stage('DB Seed') {
            steps {
                sh '''
                    cd ./backend/db-seed
                    npm i
                    node ./seed mongodb://masteries:WSR2yDDfzn7Ztj4t@mastery.att.io:27017/masteries?authSource=admin -n masteries
                '''
            }
        }
    }
}